import{parseColor,parseHex,parseRgb,parseHsl,parseHsv,parseCmyk,rgbToHex,rgbToHsl,hslToRgb,rgbToHsv,hsvToRgb,rgbToCmyk,cmykToRgb,formatRgb,formatHsl,formatHsv,formatCmyk,deterministicPalette,gradientCss,mixColors,adjustLightness,rotateHue,wcagReport,lookupColorName,seededRandomColors,alphaComposite}from"./engine.js";
const one=(id,label="Color",placeholder="#3366CC")=>({id,label,placeholder});
const conversion=(id,input,convert)=>({id,kind:"convert",inputs:[one(id+"-input",input)],convert});
const rgbFormats=color=>({hex:rgbToHex(color,color.a<1),rgb:formatRgb(color),hsl:formatHsl(rgbToHsl(color)),hsv:formatHsv(rgbToHsv(color)),cmyk:formatCmyk(rgbToCmyk(color))});
export const colorToolDefinitions={
 "hex-to-rgb":conversion("hex-to-rgb","HEX color",value=>{const color=parseHex(value);return{output:formatRgb(color),colors:[rgbToHex(color,true)]};}),
 "rgb-to-hex":{...conversion("rgb-to-hex","RGB color",value=>{const color=parseRgb(value);return{output:rgbToHex(color,color.a<1),colors:[rgbToHex(color,true)]};}),inputs:[one("rgb-to-hex-input","RGB color","rgb(51, 102, 204)")]},
 "hex-to-hsl":conversion("hex-to-hsl","HEX color",value=>{const color=parseHex(value);return{output:formatHsl(rgbToHsl(color)),colors:[rgbToHex(color,true)]};}),
 "hsl-to-hex":{...conversion("hsl-to-hex","HSL color",value=>{const color=hslToRgb(parseHsl(value));return{output:rgbToHex(color,color.a<1),colors:[rgbToHex(color,true)]};}),inputs:[one("hsl-to-hex-input","HSL color","hsl(220, 60%, 50%)")]},
 "rgb-to-hsl":{...conversion("rgb-to-hsl","RGB color",value=>{const color=parseRgb(value);return{output:formatHsl(rgbToHsl(color)),colors:[rgbToHex(color,true)]};}),inputs:[one("rgb-to-hsl-input","RGB color","rgb(51, 102, 204)")]},
 "hsl-to-rgb":{...conversion("hsl-to-rgb","HSL color",value=>{const color=hslToRgb(parseHsl(value));return{output:formatRgb(color),colors:[rgbToHex(color,true)]};}),inputs:[one("hsl-to-rgb-input","HSL color","hsl(220, 60%, 50%)")]},
 "hex-to-cmyk":conversion("hex-to-cmyk","HEX color",value=>{const color=parseHex(value);return{output:formatCmyk(rgbToCmyk(color)),colors:[rgbToHex(color)]};}),
 "cmyk-to-hex":{...conversion("cmyk-to-hex","CMYK color",value=>{const color=cmykToRgb(parseCmyk(value));return{output:rgbToHex(color),colors:[rgbToHex(color)]};}),inputs:[one("cmyk-to-hex-input","CMYK color","cmyk(0%, 50%, 100%, 0%)")]},
 "rgb-to-hsv":{...conversion("rgb-to-hsv","RGB color",value=>{const color=parseRgb(value);return{output:formatHsv(rgbToHsv(color)),colors:[rgbToHex(color,true)]};}),inputs:[one("rgb-to-hsv-input","RGB color","rgb(51, 102, 204)")]},
 "hsv-to-rgb":{...conversion("hsv-to-rgb","HSV color",value=>{const color=hsvToRgb(parseHsv(value));return{output:formatRgb(color),colors:[rgbToHex(color,true)]};}),inputs:[one("hsv-to-rgb-input","HSV color","hsv(220, 75%, 80%)")]},
 "color-picker":{id:"color-picker",kind:"picker",inputs:[{...one("color-picker-manual","Manual color"),value:"#3366CC"}],convert:value=>{const color=parseColor(value);return{output:Object.values(rgbFormats(color)).join("\n"),colors:[rgbToHex(color,true)]};}},
 "random-color-generator":{id:"random-color-generator",kind:"generator",inputs:[one("random-color-generator-input","Seed","AllTools")],convert:value=>{const colors=seededRandomColors(value,5);return{output:colors.join("\n"),colors};}},
 "color-palette-generator":{id:"color-palette-generator",kind:"palette",inputs:[one("color-palette-generator-input")],convert:value=>{const colors=deterministicPalette(value,6,"palette");return{output:colors.join("\n"),colors};}},
 "complementary-color-generator":{id:"complementary-color-generator",kind:"palette",inputs:[one("complementary-color-generator-input")],convert:value=>{const colors=deterministicPalette(value,2,"complementary");return{output:colors.join("\n"),colors};}},
 "analogous-color-generator":{id:"analogous-color-generator",kind:"palette",inputs:[one("analogous-color-generator-input")],convert:value=>{const colors=deterministicPalette(value,5,"analogous");return{output:colors.join("\n"),colors};}},
 "triadic-color-generator":{id:"triadic-color-generator",kind:"palette",inputs:[one("triadic-color-generator-input")],convert:value=>{const colors=deterministicPalette(value,3,"triadic");return{output:colors.join("\n"),colors};}},
 "tint-shade-generator":{id:"tint-shade-generator",kind:"palette",inputs:[one("tint-shade-generator-input")],convert:value=>{const color=parseColor(value),colors=[-40,-25,-10,0,10,25,40].map(amount=>rgbToHex(adjustLightness(color,amount)));return{output:colors.join("\n"),colors};}},
 "color-mixer":{id:"color-mixer",kind:"multi",inputs:[one("color-mixer-first","First color"),one("color-mixer-second","Second color","#FFCC00")],controls:[{id:"weight",label:"Second color weight",component:"field.select",value:"0.5",options:[{value:"0.25",label:"25%"},{value:"0.5",label:"50%"},{value:"0.75",label:"75%"}]}],convert:(value,options,values)=>{const mixed=mixColors(parseColor(values[0]),parseColor(values[1]),Number(options.weight));return{output:rgbToHex(mixed,true),colors:[rgbToHex(parseColor(values[0]),true),rgbToHex(mixed,true),rgbToHex(parseColor(values[1]),true)]};}},
 "gradient-generator":{id:"gradient-generator",kind:"multi",download:true,inputs:[one("gradient-generator-first","First stop"),one("gradient-generator-second","Second stop","#FFCC00"),one("gradient-generator-third","Third stop","#CC33FF")],controls:[{id:"direction",label:"Direction",component:"field.select",value:"90deg",options:["0deg","45deg","90deg","135deg","180deg","to right","to bottom"].map(value=>({value,label:value}))}],convert:(value,options,values)=>{const colors=values.map(color=>rgbToHex(parseColor(color),true)),output=gradientCss(colors,options.direction);return{output,colors,gradient:output};}},
 "contrast-checker":{id:"contrast-checker",kind:"contrast",inputs:[one("contrast-checker-first","Text color","#111827"),one("contrast-checker-second","Background color","#FFFFFF")],convert:(value,options,values)=>{const first=parseColor(values[0]),second=parseColor(values[1]),report=wcagReport(first,second);return{output:`Contrast ratio: ${report.ratio}:1\nNormal text — AA: ${report.normalAA?"Pass":"Fail"}, AAA: ${report.normalAAA?"Pass":"Fail"}\nLarge text — AA: ${report.largeAA?"Pass":"Fail"}, AAA: ${report.largeAAA?"Pass":"Fail"}`,colors:[rgbToHex(first),rgbToHex(second)],report};}},
 "wcag-color-accessibility-checker":{id:"wcag-color-accessibility-checker",kind:"contrast",inputs:[one("wcag-color-accessibility-checker-first","Foreground","#767676"),one("wcag-color-accessibility-checker-second","Background","#FFFFFF")],convert:(value,options,values)=>colorToolDefinitions["contrast-checker"].convert(value,options,values)},
 "css-color-converter":{id:"css-color-converter",kind:"convert",inputs:[one("css-color-converter-input","CSS color")],convert:value=>{const color=parseColor(value);return{output:Object.entries(rgbFormats(color)).map(([key,item])=>`${key.toUpperCase()}: ${item}`).join("\n"),colors:[rgbToHex(color,true)]};}},
 "color-name-lookup":{id:"color-name-lookup",kind:"convert",inputs:[one("color-name-lookup-input","Color name or value","coral")],convert:value=>{const result=lookupColorName(value);return{output:`${result.name}: ${result.hex}`,colors:[result.hex]};}},
 "opacity-alpha-calculator":{id:"opacity-alpha-calculator",kind:"multi",inputs:[one("opacity-alpha-calculator-first","Foreground","#3366CC80"),one("opacity-alpha-calculator-second","Background","#FFFFFF")],convert:(value,options,values)=>{const foreground=parseColor(values[0]),background=parseColor(values[1]),result=alphaComposite(foreground,background);return{output:`${formatRgb(foreground)} over ${rgbToHex(background)} = ${rgbToHex(result)}`,colors:[rgbToHex(foreground,true),rgbToHex(result)]};}},
 "lighten-darken-color":{id:"lighten-darken-color",kind:"palette",inputs:[one("lighten-darken-color-input")],convert:value=>{const color=parseColor(value),colors=[-30,-20,-10,0,10,20,30].map(amount=>rgbToHex(adjustLightness(color,amount)));return{output:colors.join("\n"),colors};}}
};
export const colorToolIds=Object.keys(colorToolDefinitions);
