import test from "node:test";
import assert from "node:assert/strict";
import{parseHex,parseRgb,parseHsl,parseHsv,parseCmyk,rgbToHex,rgbToHsl,hslToRgb,rgbToHsv,hsvToRgb,rgbToCmyk,cmykToRgb,contrastRatio,wcagReport,gradientCss,deterministicPalette,parseColor,alphaComposite}from"../src/plugins/families/color-tools/engine.js";
import{colorToolDefinitions,colorToolIds}from"../src/plugins/families/color-tools/definitions.js";
import{createToolUseTracker}from"../src/core/telemetry/tool-use.js";

const close=(actual,expected,tolerance=1)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} should be close to ${expected}`);
test("color family contains exactly 25 production definitions",()=>{assert.equal(colorToolIds.length,25);for(const id of colorToolIds){assert.equal(colorToolDefinitions[id].id,id);assert.ok(colorToolDefinitions[id].inputs.length);}});
test("HEX and RGB conversion supports alpha",()=>{assert.deepEqual(parseHex("#369"),{r:51,g:102,b:153,a:1});assert.equal(rgbToHex(parseRgb("rgba(51, 102, 153, 0.5)"),true),"#33669980");assert.equal(parseHex("#33669980").a,0.502);assert.equal(parseRgb("rgb(1, 2, 3 / 50%)").a,.5);});
test("HSL conversion round trips RGB",()=>{const source={r:51,g:102,b:204,a:.4};const result=hslToRgb(rgbToHsl(source));close(result.r,source.r);close(result.g,source.g);close(result.b,source.b);assert.equal(result.a,.4);assert.equal(parseHsl("hsl(220 60% 50% / 40%)").a,.4);});
test("HSV conversion round trips RGB",()=>{const source={r:255,g:128,b:0,a:.25};const result=hsvToRgb(rgbToHsv(source));close(result.r,source.r);close(result.g,source.g);close(result.b,source.b);assert.equal(result.a,.25);assert.equal(parseHsv("hsv(30, 100%, 100%, 25%)").a,.25);});
test("CMYK conversion handles black and round trips representative colors",()=>{assert.deepEqual(rgbToCmyk({r:0,g:0,b:0}),{c:0,m:0,y:0,k:100,a:1});const source={r:42,g:120,b:210};const result=cmykToRgb(rgbToCmyk(source));close(result.r,source.r);close(result.g,source.g);close(result.b,source.b);assert.deepEqual(parseCmyk("0, 50, 100, 0"),{c:0,m:50,y:100,k:0,a:1});});
test("invalid color inputs produce clear errors",()=>{assert.throws(()=>parseHex("#12"),/valid/);assert.throws(()=>parseRgb("300, 0, 0"),/between 0 and 255/);assert.throws(()=>parseHsl("hsl(0, 120%, 50%)"),/0–100/);assert.throws(()=>parseHsv("hsv(0, 20%, -1%)"),/0–100/);assert.throws(()=>parseColor("not-a-color"),/valid HEX/);});
test("WCAG contrast calculation reports AA and AAA accurately",()=>{assert.equal(contrastRatio(parseHex("#000"),parseHex("#FFF")),21);assert.deepEqual(wcagReport(parseHex("#777"),parseHex("#FFF")),{ratio:4.48,normalAA:false,normalAAA:false,largeAA:true,largeAAA:false});});
test("gradient output validates stops and creates deterministic CSS",()=>{assert.equal(gradientCss(["#000","#FFF","#F00"],"45deg"),"linear-gradient(45deg, #000000 0%, #FFFFFF 50%, #FF0000 100%)");assert.throws(()=>gradientCss(["#000"]),/at least two/);});
test("palette generation is deterministic and copyable",()=>{const first=deterministicPalette("#3366CC",6,"palette");assert.deepEqual(first,deterministicPalette("#3366CC",6,"palette"));assert.equal(first.length,6);assert.ok(first.every(value=>/^#[0-9A-F]{6}$/.test(value)));});
test("alpha compositing produces the expected visible color",()=>{assert.equal(rgbToHex(alphaComposite(parseHex("#00000080"),parseHex("#FFFFFF"))),"#7F7F7F");});
test("shared color telemetry deduplicates meaningful use and excludes values",()=>{const events=[];let callback;const tracker=createToolUseTracker({telemetry:{trackToolUse:event=>events.push(event)},toolId:"hex-to-rgb",category:"color",debounceMs:1,setTimer:fn=>{callback=fn;return 1;},clearTimer(){}});tracker.observe(true);tracker.observe(true);callback();tracker.observe(true);assert.deepEqual(events,[{toolId:"hex-to-rgb",category:"color",source:"meaningful_input"}]);assert.deepEqual(Object.keys(events[0]).sort(),["category","source","toolId"]);});
for(const id of colorToolIds)test(`${id} returns copyable output and previews`,()=>{const definition=colorToolDefinitions[id];const values=definition.inputs.map(input=>input.value??input.placeholder);const options=Object.fromEntries((definition.controls??[]).map(control=>[control.id,control.value]));const result=definition.convert(values[0],options,values);assert.ok(result.output);assert.ok(result.colors?.length);});
