import{generatePassword,analyzePassword,generateRandomString,generateToken,hashText,hmacText,checksum,generatePassphrase,generatePin,generateUuidV7}from"./engine.js";
const option=(value,label=value)=>({value,label});const select=(id,label,options,value)=>({id,label,component:"field.select",options,value});const input=(id,label,value,type="text")=>({id,label,component:"field.input",value,type});const check=(id,label,checked=true)=>({id,label,component:"field.checkbox",checked});
export const securityDefinitions={
 "password-generator":{id:"password-generator",mode:"generator",controls:[input("length","Length","20","number"),check("lower","Lowercase"),check("upper","Uppercase"),check("numbers","Numbers"),check("symbols","Symbols"),check("excludeAmbiguous","Exclude ambiguous",true)],run:options=>generatePassword(options)},
 "password-strength-checker":{id:"password-strength-checker",mode:"analyzer",sensitive:true,inputLabel:"Password",inputType:"password",run:value=>{const result=analyzePassword(value);return{output:`Strength: ${result.label}\nEstimated search space: ${result.entropy} bits\nSuggestions:\n- ${result.suggestions.join("\n- ")}`};}},
 "random-string-generator":{id:"random-string-generator",mode:"generator",controls:[input("length","Length","32","number"),check("lower","Lowercase"),check("upper","Uppercase"),check("numbers","Numbers"),check("symbols","Symbols",false),input("customAlphabet","Custom alphabet (optional)","")],run:options=>generateRandomString(options)},
 "secure-token-generator":{id:"secure-token-generator",mode:"generator",controls:[select("bytes","Byte length",[16,24,32,48,64].map(value=>option(String(value),`${value} bytes`)),"32"),select("format","Encoding",[option("hex","HEX"),option("base64","Base64"),option("base64url","Base64URL")],"hex")],run:options=>generateToken(options)},
 "hash-generator":{id:"hash-generator",mode:"input",inputLabel:"Text",controls:[select("algorithm","Algorithm",["sha-1","sha-256","sha-384","sha-512"].map(value=>option(value,value.toUpperCase())),"sha-256"),select("format","Output",[option("hex","HEX"),option("base64","Base64")],"hex")],run:async(value,options)=>`${options.algorithm==="sha-1"?"Warning: SHA-1 is legacy and should not protect new security-sensitive data.\n":""}${await hashText(value,options)}`},
 "hmac-generator":{id:"hmac-generator",mode:"input",inputLabel:"Message",controls:[input("key","Secret key","","password"),select("algorithm","Algorithm",["sha-256","sha-384","sha-512"].map(value=>option(value,value.toUpperCase())),"sha-256"),select("format","Output",[option("hex","HEX"),option("base64","Base64")],"hex")],run:(value,options)=>hmacText(value,options.key,options)},
 "checksum-calculator":{id:"checksum-calculator",mode:"input",inputLabel:"Text",controls:[select("algorithm","Checksum",[option("crc32","CRC32"),option("adler32","Adler-32"),option("sum8","Sum-8")],"crc32")],run:(value,options)=>`Checksum (not a cryptographic hash): ${checksum(value,options.algorithm)}`},
 "passphrase-generator":{id:"passphrase-generator",mode:"generator",controls:[select("words","Word count",[4,5,6,7,8].map(value=>option(String(value),String(value))),"5"),select("separator","Separator",[option("-","Hyphen"),option("_","Underscore"),option(" ","Space"),option(".","Period")],"-"),check("capitalize","Capitalize words",false),check("number","Append number",false)],run:options=>generatePassphrase(options)},
 "pin-generator":{id:"pin-generator",mode:"generator",controls:[select("length","Digits",[4,5,6,8,10,12].map(value=>option(String(value),String(value))),"6"),check("excludeRepeated","Exclude all-repeated PINs",true),check("excludeSequential","Exclude simple sequences",true)],run:options=>generatePin(options)},
 "uuid-v7-generator":{id:"uuid-v7-generator",mode:"generator",controls:[input("amount","Number of UUIDs","1","number")],download:true,run:options=>generateUuidV7(options)}
};
export const securityToolIds=Object.keys(securityDefinitions);
