const encoder=new TextEncoder();
const clampInt=(value,min,max,label)=>{const number=Number(value);if(!Number.isInteger(number)||number<min||number>max)throw new Error(`${label} must be a whole number between ${min} and ${max}.`);return number;};
const cryptoApi=provider=>provider??globalThis.crypto;
export function secureBytes(length,provider){const size=clampInt(length,1,65536,"Byte length"),api=cryptoApi(provider);if(!api?.getRandomValues)throw new Error("Secure random generation is unavailable in this browser.");const bytes=new Uint8Array(size);api.getRandomValues(bytes);return bytes;}
export function bytesToHex(bytes){return Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("");}
export function bytesToBase64(bytes){let binary="";for(const value of bytes)binary+=String.fromCharCode(value);return btoa(binary);}
export const bytesToBase64Url=bytes=>bytesToBase64(bytes).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"");
function pick(alphabet,provider){if(!alphabet.length)throw new Error("Choose at least one character group.");const api=cryptoApi(provider);if(!api?.getRandomValues)throw new Error("Secure random generation is unavailable in this browser.");const max=256-256%alphabet.length;let value;do value=secureBytes(1,api)[0];while(value>=max);return alphabet[value%alphabet.length];}
function shuffle(values,provider){for(let index=values.length-1;index>0;index--){let selected;do selected=secureBytes(2,provider)[0]*256+secureBytes(2,provider)[1];while(selected>=65536-65536%(index+1));const target=selected%(index+1);[values[index],values[target]]=[values[target],values[index]];}return values;}
const groups={lower:"abcdefghijklmnopqrstuvwxyz",upper:"ABCDEFGHIJKLMNOPQRSTUVWXYZ",numbers:"0123456789",symbols:"!@#$%^&*()-_=+[]{};:,.?"};
const ambiguous=new Set("Il1O0o|`'\"");
export function generatePassword(options={},provider){const length=clampInt(options.length??20,4,256,"Password length"),selected=Object.entries(groups).filter(([name])=>options[name]!==false);if(!selected.length)throw new Error("Select at least one character group.");if(length<selected.length)throw new Error("Length must fit at least one character from every selected group.");const clean=text=>options.excludeAmbiguous?[...text].filter(char=>!ambiguous.has(char)).join(""):text;const usable=selected.map(([name,chars])=>[name,clean(chars)]);if(usable.some(([,chars])=>!chars))throw new Error("A selected character group has no usable characters.");const all=usable.map(([,chars])=>chars).join("");const result=usable.map(([,chars])=>pick(chars,provider));while(result.length<length)result.push(pick(all,provider));return shuffle(result,provider).join("");}
export function analyzePassword(value){const password=String(value??"");if(!password)return{score:0,label:"Empty",entropy:0,suggestions:["Enter a password to analyze."]};let score=0,suggestions=[];if(password.length>=12)score++;else suggestions.push("Use at least 12 characters.");if(password.length>=16)score++;const diversity=[/[a-z]/,/[A-Z]/,/\d/,/[^A-Za-z0-9]/].filter(pattern=>pattern.test(password)).length;if(diversity>=3)score++;else suggestions.push("Mix uppercase, lowercase, numbers and symbols.");if(!/(.)\1{2,}/u.test(password))score++;else suggestions.push("Avoid repeated characters.");if(!/(?:password|qwerty|1234|abcd|letmein|admin)/i.test(password))score++;else suggestions.push("Avoid common words and keyboard patterns.");const pool=(/[a-z]/.test(password)?26:0)+(/[A-Z]/.test(password)?26:0)+(/\d/.test(password)?10:0)+(/[^A-Za-z0-9]/.test(password)?32:0);const entropy=pool?Math.round(password.length*Math.log2(pool)):0;const labels=["Very weak","Weak","Fair","Good","Strong","Very strong"];return{score,label:labels[score],entropy,suggestions:suggestions.length?suggestions:["No obvious local checks failed; unique passwords still matter."]};}
export function generateRandomString(options={},provider){const length=clampInt(options.length??32,1,4096,"String length");let alphabet=options.customAlphabet?.trim()||"";if(!alphabet){if(options.lower!==false)alphabet+=groups.lower;if(options.upper!==false)alphabet+=groups.upper;if(options.numbers!==false)alphabet+=groups.numbers;if(options.symbols)alphabet+=groups.symbols;}alphabet=[...new Set(alphabet)].join("");if(alphabet.length<2||alphabet.length>256)throw new Error("The alphabet must contain between 2 and 256 unique characters.");return Array.from({length},()=>pick(alphabet,provider)).join("");}
export function generateToken(options={},provider){const bytes=secureBytes(options.bytes??32,provider),format=options.format??"hex";if(format==="hex")return bytesToHex(bytes);if(format==="base64")return bytesToBase64(bytes);if(format==="base64url")return bytesToBase64Url(bytes);throw new Error("Choose a supported token encoding.");}
const digestName=value=>({"sha-1":"SHA-1","sha-256":"SHA-256","sha-384":"SHA-384","sha-512":"SHA-512"}[String(value).toLowerCase()]);
export async function hashText(value,options={},provider){const algorithm=digestName(options.algorithm??"sha-256");if(!algorithm)throw new Error("Choose SHA-1, SHA-256, SHA-384 or SHA-512.");const api=cryptoApi(provider);if(!api?.subtle)throw new Error("Web Crypto hashing is unavailable in this browser.");const bytes=new Uint8Array(await api.subtle.digest(algorithm,encoder.encode(String(value??""))));return options.format==="base64"?bytesToBase64(bytes):bytesToHex(bytes);}
export async function hmacText(message,key,options={},provider){if(!String(key??"").length)throw new Error("Enter a secret key.");const algorithm=digestName(options.algorithm??"sha-256");if(!algorithm||algorithm==="SHA-1")throw new Error("Choose SHA-256, SHA-384 or SHA-512 for HMAC.");const api=cryptoApi(provider);if(!api?.subtle)throw new Error("Web Crypto HMAC is unavailable in this browser.");const cryptoKey=await api.subtle.importKey("raw",encoder.encode(String(key)),{name:"HMAC",hash:algorithm},false,["sign"]);const bytes=new Uint8Array(await api.subtle.sign("HMAC",cryptoKey,encoder.encode(String(message??""))));return options.format==="base64"?bytesToBase64(bytes):bytesToHex(bytes);}
const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;table[n]=c>>>0;}return table;})();
export function checksum(value,algorithm="crc32"){const bytes=encoder.encode(String(value??""));if(algorithm==="crc32"){let crc=0xFFFFFFFF;for(const item of bytes)crc=crcTable[(crc^item)&0xFF]^(crc>>>8);return((crc^0xFFFFFFFF)>>>0).toString(16).padStart(8,"0");}if(algorithm==="adler32"){let a=1,b=0;for(const item of bytes){a=(a+item)%65521;b=(b+a)%65521;}return(((b<<16)|a)>>>0).toString(16).padStart(8,"0");}if(algorithm==="sum8")return(bytes.reduce((sum,item)=>(sum+item)&255,0)).toString(16).padStart(2,"0");throw new Error("Choose CRC32, Adler-32 or Sum-8.");}
export const passphraseWords=Object.freeze("amber anchor apple apron atlas autumn bamboo beacon berry birch breeze brook cedar circle cloud comet coral crystal dawn delta dune eagle ember field flame forest frost garden globe harbor hazel island ivory juniper lantern lemon lunar maple meadow mist mountain ocean olive orbit pebble pine pixel quartz raven river robin silver solar sparrow stone storm summit sunset timber tulip valley velvet violet willow winter zephyr".split(" "));
export function generatePassphrase(options={},provider){const count=clampInt(options.words??5,3,12,"Word count"),separator=String(options.separator??"-").slice(0,8),chosen=Array.from({length:count},()=>pick(passphraseWords,provider));if(options.capitalize)for(let index=0;index<chosen.length;index++)chosen[index]=chosen[index][0].toUpperCase()+chosen[index].slice(1);let result=chosen.join(separator);if(options.number)result+=separator+pick(groups.numbers,provider);return result;}
const sequential=value=>"0123456789 9876543210".split(" ").some(sequence=>sequence.includes(value));
export function generatePin(options={},provider){const length=clampInt(options.length??6,4,12,"PIN length");for(let attempt=0;attempt<1000;attempt++){const value=Array.from({length},()=>pick(groups.numbers,provider)).join("");if(options.excludeRepeated&&new Set(value).size===1)continue;if(options.excludeSequential&&sequential(value))continue;return value;}throw new Error("Could not satisfy the selected PIN constraints. Try a longer PIN.");}
export function uuidV7(timestamp=Date.now(),provider){const time=Number(timestamp);if(!Number.isInteger(time)||time<0||time>0xFFFFFFFFFFFF)throw new Error("UUID v7 timestamp is outside the supported range.");const random=secureBytes(10,provider),bytes=new Uint8Array(16);let current=BigInt(time);for(let index=5;index>=0;index--){bytes[index]=Number(current&255n);current>>=8n;}bytes.set(random.slice(0,10),6);bytes[6]=(bytes[6]&0x0F)|0x70;bytes[8]=(bytes[8]&0x3F)|0x80;const hex=bytesToHex(bytes);return`${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;}
export function generateUuidV7(options={},provider){const count=clampInt(options.amount??1,1,100,"UUID count"),start=options.now??Date.now();return Array.from({length:count},(_,index)=>uuidV7(start+index,provider)).join("\n");}
