import{securityDefinitions}from"./definitions.js";
import{createToolUseTracker}from"../../../core/telemetry/tool-use.js";

let cleanup;
const labels={generate:["Generate","generator"],paste:["Paste","paste"],clear:["Clear","clear"],copy:["Copy result","copy"],download:["Download","download"]};
export function mount(root,context){
 const definition=securityDefinitions[context.toolId];if(!definition)throw new Error(`Unknown security tool: ${context.toolId}`);
 const generator=definition.mode==="generator",tracker=createToolUseTracker({telemetry:context.telemetry,toolId:context.toolId,category:"security"});
 const actionIds=generator?["generate","copy",...(definition.download?["download"]:[])]:["paste","clear","copy"];
 const shell=context.components.create("tool.shell",{toolbarLabel:"Security tool actions",actions:actionIds.map(id=>({id,label:labels[id][0],icon:labels[id][1],variant:id==="generate"?"primary":"secondary"})),controls:definition.controls??[],editor:generator?null:{id:`${definition.id}-input`,component:"field.input",type:definition.inputType??"text",label:definition.inputLabel??"Input",placeholder:definition.sensitive?"Enter locally for analysis":"Enter text",autofocus:true},output:{id:`${definition.id}-output`,component:"field.textarea",label:"Result",rows:7}});
 root.replaceChildren(shell.element);let last="",runId=0;const handlers=[];const on=(element,event,handler)=>{element.addEventListener(event,handler);handlers.push(()=>element.removeEventListener(event,handler));};
 const options=()=>Object.fromEntries([...shell.controls].map(([id,control])=>[id,control.input.type==="checkbox"?control.input.checked:control.input.value]));
 const update=async({meaningful=false}={})=>{const current=++runId;if(!generator&&!shell.input.value){last="";shell.output.value="";shell.notice.clear();tracker.observe(false);return;}try{const result=await definition.run(generator?options():shell.input.value,options());if(current!==runId)return;last=String(result?.output??result??"");shell.output.value=last;shell.notice.clear();tracker.observe(generator?meaningful:Boolean(shell.input.value));}catch(error){if(current!==runId)return;last="";shell.output.value="";shell.notice.show(error.message||"The operation could not be completed.",0);tracker.observe(false);}};
 if(shell.input)on(shell.input,"input",()=>update());for(const control of shell.controls.values()){on(control.input,"input",()=>generator?undefined:update());on(control.input,"change",()=>generator?undefined:update());}
 const generate=()=>update({meaningful:true});const paste=async()=>{try{shell.input.value=await context.clipboard.readText();await update();shell.input.focus();context.telemetry.trackPaste({toolId:context.toolId,category:"security"});}catch{shell.notice.show("Paste permission was not available.");}};const clear=()=>{shell.input.value="";update();shell.input.focus();context.telemetry.trackClear({toolId:context.toolId,category:"security"});};const copy=async()=>{if(!last)return shell.notice.show("There is no result to copy.");try{await context.clipboard.writeText(last);shell.notice.show("Result copied.");context.telemetry.trackCopy({toolId:context.toolId,category:"security"});}catch{shell.notice.show("Copy was not available.");}};const download=()=>{if(!last)return shell.notice.show("There is no result to download.");const url=URL.createObjectURL(new Blob([last+"\n"],{type:"text/plain;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`${context.toolId}.txt`;link.click();URL.revokeObjectURL(url);context.telemetry.trackDownload({toolId:context.toolId,category:"security"});};
 for(const[id,handler]of Object.entries({generate,paste,clear,copy,download}))if(shell.actions.has(id))on(shell.actions.get(id).element,"click",handler);
 if(generator)update();else update();cleanup=()=>{runId++;for(const remove of handlers)remove();tracker.cancel();shell.notice.clear();if(shell.input)shell.input.value="";for(const control of shell.controls.values())if(control.input.type==="password")control.input.value="";};
}
export function unmount(){cleanup?.();cleanup=undefined;}
